### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=PyCharm

###

# curl -X 'POST'   'http://127.0.0.1:5000/api/flamegraphs/3/'   -H 'accept: */*'   -H 'Content-Type: multipart/form-data'   -F 'file=@filteredClusterMonitoringDebug.svg;type=image/svg+xml'
POST http://127.0.0.1:5000/api/flamegraphs/1/
accept: */*
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="../../filteredClusterMonitoringDebug.svg"

< filteredClusterMonitoringDebug.svg
--WebAppBoundary--

###

